RunAction "OpenChrome&URL", oneIteration
RunAction "LoginBPM", oneIteration
RunAction "FillDiscoForm", oneIteration
RunAction "FilterDisco_WR", oneIteration
RunAction "Claim&SetPriority", oneIteration
RunAction "Claim&DisconnectTask", oneIteration
RunAction "BuildAIP", oneIteration
RunAction "ClaimRevokeAssign", oneIteration
RunAction "CreateDuplicateDisco", oneIteration
RunAction "DiscoConfiguration", oneIteration
RunAction "DiscoSearch", oneIteration
RunAction "ClaimMultipleDiscoTask", oneIteration
RunAction "ResultToOutlook", oneIteration
